### ISSUE TITLE
Ruby client gem

### ISSUE THREAD

**Issue by jamonholmgren** [countitlabs/omniauth-shine#1]
Hi @mathiasxx! Do you know of any ruby client gem for the Misfit Shine Open API? I'm having trouble finding anything.

**Comment by mathiasxx** [comment]
hi, you can try the one I hacked up.  Maybe together we can make it solid.
https://github.com/socialworkout/shine

**Comment by jamonholmgren** [comment]
Cool, thanks. We will likely need it in the next 4 weeks or so, so we'll contribute.
