### ISSUE TITLE
Missing from Rubygems?

### ISSUE THREAD

**Issue by eblohm** [countitlabs/omniauth-shine#2]
Is this gem not on Rubygems.org anymore? I'm trying to integrate it into my website, but I get an error whenever I run bundle install, and searching rubygems.org returns nothing.

**Comment by eblohm** [comment]
Figured it out - built the gem locally

**Comment by mathiasxx** [comment]
```
gem 'omniauth-shine', github: 'socialworkout/omniauth-shine'
```
